version: '3.9'

services:

  theater_service:
    container_name: theater_service
    build: ./theater_service/
    ports:
      - "8000:80"

  tickets_service:
    restart: on-failure
    container_name: tickets_service
    build: tickets_service/
    ports:
      - "8001:80"